'use client'
import './globals.css'
import { Inter } from 'next/font/google'
import Sidebar from "../components/Sidebar";
import { useEffect, useState } from 'react';
import classNames from 'classnames';
import { usePathname } from 'next/navigation'

//Esto es para que se pueda usar la fuente de google fonts

const inter = Inter({ subsets: ['latin'] })

//Esta es la metadata de la página, la metadata es la información que se muestra en la pestaña del navegador
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

//Esta es la función que se encarga de renderizar el layout de la página
export default function RootLayout({
  children, //Esto es para que se pueda renderizar el contenido de la página, children es el contenido de la página
}: {
  children: React.ReactNode //Esto significa que children es un nodo de react, sirve para que se pueda renderizar el contenido de la página
}) {
  const [collapsed, setSidebarCollapsed] = useState(false); //Esto es para que se pueda colapsar el sidebar, collapsed es un booleano que indica si el sidebar está colapsado o no
  const [showSidebar, setShowSidebar] = useState(true);

  //Esto es para que se pueda saber en que página se encuentra el usuario
  const pathname = usePathname();

  /**
   * This effect is used to hide the sidebar when the user is on the login or signup page
   */
  useEffect(() => {
    if (pathname === '/auth/login' || pathname === '/auth/signup' || pathname === '/req-access') {

      setShowSidebar(false);
    } else {
      setShowSidebar(true);
    }
  }, [pathname]);


  //setShowSidebar(false); Para que no se muestre el sidebar

  /**
   * This is the layout of the page, it renders the sidebar and the content of the page
   * Esto es el layout de la página, renderiza el sidebar y el contenido de la página, el layout es la estructura de la página
   */
  return (
    <html lang="en">
      <body
      >
        <div className='flex h-screen'>
          {showSidebar && (
            <Sidebar
              collapsed={collapsed}
              setCollapsed={setSidebarCollapsed}
              shown={showSidebar}
            />
          )}
          {children}
        </div>
      </body>
    </html>
  );
}
